version: "3.7"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcendence
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    networks:
      - default

  
  # frontend:
  #   build: 
  #     context: ./front-end
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./front-end/src:/app/src
  #   restart: always
  #   networks:
  #     - default

  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    environment:
      GRPC_TRACE: all
      GRPC_VERBOSITY: DEBUG
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/transcendence?schema=public
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/prisma:/usr/src/app/prisma
      - ./backend/uploads:/usr/src/app/uploads
    depends_on:
      - postgres
    ports:
      - 3000:3000
    restart: always
    networks:
      - default
