version: "3.7"
services:
  postgres:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transcendence
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    restart: unless-stopped
  # frontend:
  #   build:
  #     context: ./front-end
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./front-end/src:/app/src
  #   restart: always
  #   networks:
  #     - default
  # backend:
  #   build:
  #     context: ./back-end
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/transcendence?schema=public
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 3000:3000
  #   restart: always
  #   networks:
  #     - default
