version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ft_transcendence
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - default

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - default
  # frontend:
  #   build:
  #     context: ./front-end
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - 8083:8083
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./front-end/src:/app/src
  #   restart: always
  #   networks:
  #     - default
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ft_transcendence
    depends_on:
      - postgres
    ports:
      - 3001:3000
    restart: always
    networks:
      - default
