# Use an official Node.js base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY ./package*.json ./

# Copy the rest of the application code to the container
COPY . .

# Install dependencies
RUN npm install


# Expose the port that the app will run on
EXPOSE 8080

# Start the app
CMD ["npm", "start"]