FROM node:latest
WORKDIR /usr/src/app
RUN npm i -g --force yarn 
COPY package*.json ./
RUN yarn 
# RUN npm i -g prisma
COPY ./ ./
RUN yarn generate:postgres 
# RUN yarn build 
EXPOSE 3000
CMD  yarn dev
